import { useState } from 'react'
import { AlertTriangle, Download, FileCheck2, Package, X } from 'lucide-react'
import { generatePdfFn, type PdfJob, type PdfResult } from '../server/pdf'
import { generateGooglePdfFn, type GoogleFormat } from '../server/googlePdf'
import type { GoogleStatus } from '../server/google'
import { downloadDocument, downloadZip } from '../lib/download'
import { Button, ErrorNote, Spinner, useDialogChrome } from './ui'

/**
 * Modal that renders the jobs to PDF and offers the downloads. With a Google
 * account connected the PDFs are generated by Google Docs itself (exact
 * pagination, identical to the original); otherwise by the local engine
 * (approximate pagination). `warnings` lists used columns with empty cells —
 * shown before generating because a silent blank in a legal document is worse
 * than a warning (non-blocking: some columns are legitimately optional).
 */
export function GenerateDialog({
  jobs,
  google,
  warnings = [],
  onClose,
}: {
  jobs: PdfJob[]
  google: GoogleStatus | null
  warnings?: string[]
  onClose: () => void
}) {
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<PdfResult | null>(null)
  const [error, setError] = useState<{ error: string; hint?: string } | null>(null)
  const [withDocx, setWithDocx] = useState(false)

  // Escape closes — unless a generation is in flight (its result would be lost).
  useDialogChrome(() => {
    if (!loading) onClose()
  })

  const viaGoogle = google?.connected ?? false

  async function generate() {
    setLoading(true)
    setError(null)
    setResult(null)
    try {
      if (viaGoogle) {
        const formats: GoogleFormat[] = withDocx ? ['pdf', 'docx'] : ['pdf']
        const res = await generateGooglePdfFn({ data: { jobs, formats } })
        if (res.ok) setResult(res.data)
        else setError(res)
      } else {
        setResult(await generatePdfFn({ data: { jobs } }))
      }
    } catch {
      setError({
        error:
          'No se pudieron generar los PDF. Revisa que el servidor esté funcionando e inténtalo de nuevo.',
      })
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4">
      <div
        role="dialog"
        aria-modal="true"
        aria-label="Generar los documentos"
        className="max-h-[85vh] w-full max-w-lg overflow-y-auto rounded-xl border border-hairline bg-surface p-6 shadow-e2"
      >
        <div className="mb-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <FileCheck2 className="h-6 w-6 text-primary" />
            <div>
              <h2 className="text-lg font-semibold text-ink">Generar los documentos</h2>
              <p className="text-sm text-ink-muted">
                Se crearán <strong>{jobs.length}</strong> {jobs.length === 1 ? 'documento' : 'documentos'} en
                PDF.
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            aria-label="Cerrar"
            className="rounded-md p-1.5 text-ink-muted outline-none hover:bg-black/5 focus-visible:ring-2 focus-visible:ring-primary"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <p className="mb-4 rounded-lg bg-canvas-soft px-3 py-2 text-xs text-ink-muted">
          {viaGoogle ? (
            <>
              Los generará <strong>Google Docs</strong> con tu cuenta
              {google?.email ? ` (${google.email})` : ''}: los saltos de página los pone Google,
              igual que en el documento original.
            </>
          ) : (
            <>
              Se generarán con el motor local (paginación aproximada). Conecta tu cuenta de Google
              (botón arriba a la derecha) para que los genere Google Docs con paginación exacta.
            </>
          )}
        </p>

        {warnings.length > 0 && !result ? (
          <div className="mb-4 flex items-start gap-2.5 rounded-lg border border-accent-orange/30 bg-accent-orange/5 p-3 text-sm">
            <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-accent-orange" />
            <div className="text-accent-orange">
              <p className="font-medium">Hay datos en blanco (saldrán vacíos en el PDF):</p>
              <ul className="mt-1 list-inside list-disc text-xs">
                {warnings.map((w) => (
                  <li key={w}>{w}</li>
                ))}
              </ul>
              <p className="mt-1 text-xs">
                Si esas columnas son opcionales, puedes continuar sin problema.
              </p>
            </div>
          </div>
        ) : null}

        {!result ? (
          <div className="space-y-3">
            {viaGoogle ? (
              <label className="flex cursor-pointer items-center gap-2 text-sm text-ink-secondary">
                <input
                  type="checkbox"
                  checked={withDocx}
                  onChange={(e) => setWithDocx(e.target.checked)}
                  className="h-4 w-4 rounded border-input-border accent-primary"
                />
                Incluir también Word (.docx) editable
              </label>
            ) : (
              <p className="text-xs text-ink-muted">
                El formato Word (.docx) solo está disponible generando con Google (conecta tu
                cuenta arriba a la derecha).
              </p>
            )}
            <Button onClick={generate} disabled={loading}>
              {loading ? (
                <Spinner
                  label={
                    viaGoogle
                      ? withDocx
                        ? 'Generando PDF y Word con Google…'
                        : 'Generando PDF con Google…'
                      : 'Generando PDF…'
                  }
                />
              ) : (
                <>
                  <Download className="h-4 w-4" /> Generar {withDocx && viaGoogle ? 'PDF + Word' : 'PDF'}
                </>
              )}
            </Button>
          </div>
        ) : null}

        {error ? (
          <div className="mt-4">
            <ErrorNote title={error.error} hint={error.hint} />
          </div>
        ) : null}

        {result ? (
          <div className="mt-2 space-y-3">
            {result.zipBase64 ? (
              <Button onClick={() => downloadZip('documentos.zip', result.zipBase64!)}>
                <Package className="h-4 w-4" /> Descargar todo (.zip)
              </Button>
            ) : null}
            <ul className="divide-y divide-hairline/60 rounded-lg border border-hairline">
              {result.files.map((f) => (
                <li key={f.name} className="flex items-center justify-between px-4 py-2.5">
                  <span className="truncate text-sm text-ink-secondary">{f.name}</span>
                  <Button variant="secondary" onClick={() => downloadDocument(f.name, f.base64)}>
                    <Download className="h-4 w-4" /> Descargar
                  </Button>
                </li>
              ))}
            </ul>
          </div>
        ) : null}
      </div>
    </div>
  )
}
