import { useState } from 'react'
import { CircleCheck, CloudOff, Link2 } from 'lucide-react'
import { googleAuthUrlFn, googleDisconnectFn, type GoogleStatus } from '../server/google'
import { ConfirmDialog } from './ui'

/**
 * Compact Google-account chip for the header: connect (starts the OAuth
 * consent flow), or show the connected account with a disconnect action.
 * With a connected account the PDFs are generated BY Google (exact
 * pagination); without it the local engine is used (approximate).
 */
export function GoogleConnect({
  status,
  onChanged,
}: {
  status: GoogleStatus | null
  onChanged: () => void
}) {
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<{ error: string; hint?: string } | null>(null)
  const [confirmDisconnect, setConfirmDisconnect] = useState(false)

  if (!status) return null

  async function connect() {
    setBusy(true)
    setError(null)
    try {
      const res = await googleAuthUrlFn({ data: { origin: window.location.origin } })
      if (res.ok) window.location.href = res.data.url
      else {
        setError(res)
        setBusy(false)
      }
    } catch {
      setError({ error: 'No se pudo iniciar la conexión con Google.' })
      setBusy(false)
    }
  }

  async function disconnect() {
    setBusy(true)
    setError(null)
    try {
      await googleDisconnectFn()
    } finally {
      setBusy(false)
      onChanged()
    }
  }

  /** Old connection without the read permission: redo the consent flow. */
  async function reconnect() {
    setBusy(true)
    setError(null)
    try {
      await googleDisconnectFn()
    } catch {
      /* ignore: connect() below surfaces real problems */
    }
    await connect()
  }

  return (
    <div className="relative ml-auto flex items-center gap-2">
      {status.connected ? (
        <>
          <span
            className="inline-flex items-center gap-1.5 rounded-full bg-accent-green/10 px-3 py-1.5 text-xs font-medium text-accent-green"
            title="Los PDF los genera Google Docs con esta cuenta: paginación idéntica al original"
          >
            <CircleCheck className="h-3.5 w-3.5" />
            Google · {status.email ?? 'conectado'}
          </span>
          {!status.canRead ? (
            <button
              onClick={reconnect}
              disabled={busy}
              className="inline-flex items-center gap-1 rounded-full bg-accent-orange/10 px-3 py-1.5 text-xs font-medium text-accent-orange hover:bg-accent-orange/15 disabled:opacity-50"
              title="Tu conexión es anterior al permiso de lectura: reconecta para poder cargar documentos y hojas privados"
            >
              Reconectar (permiso de lectura)
            </button>
          ) : null}
          <button
            onClick={() => setConfirmDisconnect(true)}
            disabled={busy}
            className="inline-flex items-center gap-1 text-xs text-ink-faint outline-none hover:text-ink-secondary focus-visible:ring-2 focus-visible:ring-primary disabled:opacity-50"
            title="Desconectar la cuenta de Google"
          >
            <CloudOff className="h-3.5 w-3.5" /> Desconectar
          </button>
        </>
      ) : (
        <button
          onClick={connect}
          disabled={busy}
          className="inline-flex items-center gap-1.5 rounded-full border border-hairline bg-surface px-3 py-1.5 text-xs font-medium text-ink-secondary shadow-e1 hover:text-primary disabled:opacity-50"
          title="Conecta tu cuenta para que los PDF los genere Google Docs (paginación idéntica al original)"
        >
          <Link2 className="h-3.5 w-3.5" /> Conectar Google
        </button>
      )}

      {error ? (
        <div className="absolute right-0 top-full z-30 mt-2 w-80 rounded-xl border border-red-200 bg-surface p-3 shadow-e2">
          <p className="text-xs font-medium text-red-700">{error.error}</p>
          {error.hint ? <p className="mt-1 text-xs text-ink-muted">{error.hint}</p> : null}
          <button
            onClick={() => setError(null)}
            className="mt-2 text-xs font-medium text-ink-muted outline-none hover:text-ink-secondary focus-visible:ring-2 focus-visible:ring-primary"
          >
            Cerrar
          </button>
        </div>
      ) : null}

      {confirmDisconnect ? (
        <ConfirmDialog
          title="¿Desconectar la cuenta de Google?"
          body="Los PDF pasarán a generarse con el motor local (paginación aproximada) y los documentos privados dejarán de poder leerse."
          confirmLabel="Desconectar"
          onConfirm={() => {
            setConfirmDisconnect(false)
            disconnect()
          }}
          onCancel={() => setConfirmDisconnect(false)}
        />
      ) : null}
    </div>
  )
}
