import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { FileStack, Home, RotateCcw, Save } from 'lucide-react'
import { Link } from '@tanstack/react-router'
import { rehydrateStores, useWorkspace } from '../state/workspaceStore'
import type { GenerationPlan } from '../types'
import { buildTemplate } from '../lib/template/parse'
import { effectiveMapping, renderDocuments, unmappedTags } from '../lib/plan'
import { googleStatusFn, type GoogleStatus } from '../server/google'
import { DocCanvas, type DocCanvasHandle } from './DocCanvas'
import { Palette } from './Palette'
import { TopBar } from './TopBar'
import { GenerateDialog } from './GenerateDialog'
import { GoogleConnect } from './GoogleConnect'
import { PreviewFrame } from './PreviewFrame'
import { SaveRecipeDialog } from './SaveRecipeDialog'
import { ConfirmDialog, Pill, Toast } from './ui'

/**
 * The single-screen workspace: top bar (sources, grouping, preview, generate),
 * Scratch-style palette on the left, and the document canvas in the middle.
 */
export function Workspace() {
  const {
    editorHtml,
    editorCss,
    editorTitle,
    editorBodyClass,
    templateUrl,
    data,
    mapping,
    group,
    view,
    notice,
    noticeToken,
    clearNotice,
    notify,
    reset,
  } = useWorkspace()

  const canvasRef = useRef<DocCanvasHandle>(null)
  const [generateOpen, setGenerateOpen] = useState(false)
  const [previewIndex, setPreviewIndex] = useState(0)
  const [confirmReset, setConfirmReset] = useState(false)
  const [saveOpen, setSaveOpen] = useState(false)

  // Ctrl+Z / Ctrl+Y anywhere in the app (the iframe handles its own copy).
  // Skipped inside form fields, where native text undo must keep working.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      const k = e.key.toLowerCase()
      if (!(e.ctrlKey || e.metaKey) || (k !== 'z' && k !== 'y')) return
      const t = e.target as HTMLElement | null
      if (
        t &&
        (t.tagName === 'INPUT' || t.tagName === 'TEXTAREA' || t.tagName === 'SELECT' || t.isContentEditable)
      )
        return
      e.preventDefault()
      const st = useWorkspace.getState()
      const isRedo = k === 'y' || e.shiftKey
      const label = isRedo ? st.redo() : st.undo()
      if (label) st.notify(`${isRedo ? 'Rehecho' : 'Deshecho'}: ${label}`)
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [])

  // Restore the persisted workspace (client-only; idempotent across routes).
  useEffect(() => {
    void rehydrateStores()
  }, [])

  // Google connection: with an account connected, the PDFs are generated by
  // Google Docs itself (exact pagination); otherwise the local engine is used.
  const [google, setGoogle] = useState<GoogleStatus | null>(null)
  const refreshGoogle = useCallback(() => {
    googleStatusFn()
      .then(setGoogle)
      .catch(() => setGoogle(null))
  }, [])
  useEffect(refreshGoogle, [refreshGoogle])

  // The template is derived on demand from the document HTML — cheap and pure.
  const template = useMemo(
    () =>
      editorHtml.trim()
        ? buildTemplate(editorHtml, editorCss, editorTitle, templateUrl || 'editor', editorBodyClass)
        : null,
    [editorHtml, editorCss, editorTitle, templateUrl, editorBodyClass],
  )

  const unbound = unmappedTags(template, data?.columns ?? [], mapping)

  const plan: GenerationPlan | null = useMemo(() => {
    if (!template || !data) return null
    return {
      template,
      data,
      mapping: effectiveMapping(template.tags, data.columns, mapping),
      group,
    }
  }, [template, data, mapping, group])

  const previewDocs = useMemo(
    () => (view === 'preview' && plan ? renderDocuments(plan, 'placeholder') : []),
    [view, plan],
  )

  const generateBlockedReason = !template
    ? 'Escribe o carga primero la plantilla'
    : !data
      ? 'Carga primero los datos'
      : template.tags.length === 0
        ? 'Inserta al menos un campo en el documento'
        : unbound.length > 0
          ? `Faltan datos por vincular: ${unbound.join(', ')}`
          : null

  // Used columns with empty cells: a blank in a legal document is silent and
  // dangerous, so GenerateDialog shows these as a non-blocking warning.
  const emptyCellWarnings = useMemo(() => {
    if (!plan) return []
    const used = [...new Set(Object.values(plan.mapping).filter((c): c is string => !!c))]
    const warnings: string[] = []
    for (const col of used) {
      const empty = plan.data.rows.filter((r) => !(r[col] ?? '').trim()).length
      if (empty > 0) warnings.push(`«${col}» no tiene valor en ${empty} de ${plan.data.rows.length} filas`)
    }
    return warnings
  }, [plan])

  const boundCount = template ? template.tags.length - unbound.length : 0
  const hasWork = Boolean(editorHtml.trim() || data || templateUrl.trim())

  const current = previewDocs[Math.min(previewIndex, Math.max(0, previewDocs.length - 1))]

  return (
    <div className="mx-auto flex h-screen max-w-[110rem] flex-col gap-3 px-4 py-4">
      <header className="flex items-center gap-2">
        <Link
          to="/"
          className="inline-flex items-center gap-1.5 rounded-full border border-slate-300 bg-white px-2.5 py-1 text-xs font-medium text-slate-600 outline-none hover:border-indigo-300 hover:text-indigo-700 focus-visible:ring-2 focus-visible:ring-indigo-500"
        >
          <Home className="h-3.5 w-3.5" /> Inicio
        </Link>
        <FileStack className="h-5 w-5 text-indigo-600" />
        <h1 className="text-base font-bold text-slate-900">Generador de documentos</h1>
        <div className="ml-auto flex items-center gap-3">
          <button
            onClick={() => setSaveOpen(true)}
            disabled={!editorHtml.trim()}
            className="inline-flex items-center gap-1.5 rounded-full border border-slate-300 bg-white px-2.5 py-1 text-xs font-medium text-slate-600 outline-none hover:border-indigo-300 hover:text-indigo-700 focus-visible:ring-2 focus-visible:ring-indigo-500 disabled:opacity-40"
            title="Guarda el documento con sus campos, el enlace de datos, los vínculos y la agrupación en la biblioteca"
          >
            <Save className="h-3.5 w-3.5" /> Guardar plantilla
          </button>
          <GoogleConnect status={google} onChanged={refreshGoogle} />
        </div>
      </header>

      <TopBar
        canGenerate={!generateBlockedReason}
        generateBlockedReason={generateBlockedReason}
        onGenerate={() => setGenerateOpen(true)}
      />

      {/* Flow status: what is done, what is missing, why Generate is blocked
          (the reason used to live only in a hover tooltip). */}
      <div className="flex flex-wrap items-center gap-2 px-1 text-xs">
        <Pill tone={template ? 'ok' : 'muted'}>1 · Plantilla{template ? ' ✓' : ''}</Pill>
        <Pill tone={data ? 'ok' : 'muted'}>
          2 · Datos{data ? ` ✓ ${data.rows.length} ${data.rows.length === 1 ? 'fila' : 'filas'}` : ''}
        </Pill>
        <Pill
          tone={
            !template || template.tags.length === 0 ? 'muted' : unbound.length > 0 ? 'warn' : 'ok'
          }
        >
          3 · Campos{template && template.tags.length > 0 ? ` ${boundCount}/${template.tags.length} vinculados` : ''}
        </Pill>
        <span role="status" className={generateBlockedReason ? 'text-amber-700' : 'text-emerald-700'}>
          {generateBlockedReason ?? 'Listo para generar.'}
        </span>
        {group.mode === 'per_row' && editorHtml.includes('data-ttg-repeat') ? (
          <span className="text-amber-700">
            Hay secciones repetibles, pero en «un documento por fila» no se repiten: cambia a «un
            documento por grupo».
          </span>
        ) : null}
        {hasWork ? (
          <button
            onClick={() => setConfirmReset(true)}
            className="ml-auto inline-flex items-center gap-1 rounded-md px-2 py-1 text-xs text-slate-500 outline-none hover:bg-slate-100 hover:text-slate-700 focus-visible:ring-2 focus-visible:ring-indigo-500"
          >
            <RotateCcw className="h-3 w-3" /> Empezar de nuevo
          </button>
        ) : null}
      </div>

      <div className="flex min-h-0 flex-1 gap-3">
        <Palette canvas={canvasRef} />

        <main className="relative min-w-0 flex-1">
          {/* The canvas stays mounted (hidden) in preview mode so the iframe
              keeps its state; the preview renders on top. */}
          <DocCanvas ref={canvasRef} className={view === 'edit' ? 'h-full' : 'hidden'} />

          {view === 'preview' ? (
            <div className="flex h-full flex-col gap-2">
              {previewDocs.length > 1 ? (
                <label className="flex items-center gap-2 text-sm text-slate-600">
                  Ver documento
                  <select
                    value={previewIndex}
                    onChange={(e) => setPreviewIndex(Number(e.target.value))}
                    className="max-w-[18rem] rounded-lg border border-slate-300 px-2 py-1.5 text-sm outline-none focus:border-indigo-500"
                  >
                    {previewDocs.map((d, i) => (
                      <option key={i} value={i}>
                        {d.key} {d.rowCount > 1 ? `(${d.rowCount} filas)` : ''}
                      </option>
                    ))}
                  </select>
                </label>
              ) : null}
              {current ? (
                <PreviewFrame html={current.html} className="min-h-0 flex-1" />
              ) : (
                <p className="text-sm text-slate-400">Nada que previsualizar todavía.</p>
              )}
            </div>
          ) : null}
        </main>
      </div>

      {generateOpen && plan ? (
        <GenerateDialog
          jobs={renderDocuments(plan, 'empty').map((d) => ({ name: d.key, html: d.html }))}
          google={google}
          warnings={emptyCellWarnings}
          onClose={() => setGenerateOpen(false)}
        />
      ) : null}

      {confirmReset ? (
        <ConfirmDialog
          title="¿Empezar de nuevo?"
          body="Se vaciará la plantilla, los datos y los vínculos actuales. Las plantillas guardadas en «Mis plantillas» no se tocan."
          confirmLabel="Vaciar todo"
          onConfirm={() => {
            reset()
            setConfirmReset(false)
            notify('Espacio de trabajo vaciado.')
          }}
          onCancel={() => setConfirmReset(false)}
        />
      ) : null}

      {saveOpen ? <SaveRecipeDialog onClose={() => setSaveOpen(false)} /> : null}

      <Toast text={notice} token={noticeToken} onDismiss={clearNotice} />
    </div>
  )
}
