import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Check, CircleCheck, FileStack, Home, RotateCcw, Save } from 'lucide-react'
import { Link } from '@tanstack/react-router'
import { useWorkspace } from '../state/workspaceStore'
import type { GenerationPlan } from '../types'
import { buildTemplateCached } from '../lib/template/parse'
import { allPlanTags, effectiveMapping, planGroups, renderDocuments, unmappedTags } from '../lib/plan'
import { resolveGroupDocument } from '../lib/engine/resolve'
import { buildNativeJobs, decideNativeRoute } from '../lib/nativeMerge'
import { authGuard } from '../lib/authRedirect'
import { googleStatusFn, type GoogleStatus } from '../server/google'
import { DocCanvas, type DocCanvasHandle } from './DocCanvas'
import { Palette } from './Palette'
import { TopBar } from './TopBar'
import { GenerateDialog } from './GenerateDialog'
import { GoogleConnect } from './GoogleConnect'
import { PreviewFrame } from './PreviewFrame'
import { NativePreviewFrame } from './NativePreviewFrame'
import { SaveRecipeDialog } from './SaveRecipeDialog'
import { ConfirmDialog, Toast } from './ui'

/**
 * The single-screen workspace: top bar (sources, grouping, preview, generate),
 * Scratch-style palette on the left, and the document canvas in the middle.
 */
export function Workspace() {
  const {
    editorHtml,
    editorCss,
    editorTitle,
    editorBodyClass,
    templateUrl,
    sourceFile,
    data,
    mapping,
    ruleBindings,
    tagFormats,
    group,
    view,
    notice,
    noticeToken,
    clearNotice,
    notify,
    reset,
  } = useWorkspace()

  const canvasRef = useRef<DocCanvasHandle>(null)
  const [generateOpen, setGenerateOpen] = useState(false)
  const [previewIndex, setPreviewIndex] = useState(0)
  const [confirmReset, setConfirmReset] = useState(false)
  const [saveOpen, setSaveOpen] = useState(false)

  // Ctrl+Z / Ctrl+Y anywhere in the app (the iframe handles its own copy).
  // Skipped inside form fields, where native text undo must keep working.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      const k = e.key.toLowerCase()
      if (!(e.ctrlKey || e.metaKey) || (k !== 'z' && k !== 'y')) return
      const t = e.target as HTMLElement | null
      if (
        t &&
        (t.tagName === 'INPUT' || t.tagName === 'TEXTAREA' || t.tagName === 'SELECT' || t.isContentEditable)
      )
        return
      e.preventDefault()
      const st = useWorkspace.getState()
      const isRedo = k === 'y' || e.shiftKey
      const label = isRedo ? st.redo() : st.undo()
      if (label) st.notify(`${isRedo ? 'Rehecho' : 'Deshecho'}: ${label}`)
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [])

  // Google connection: with the user's connection alive, the PDFs are
  // generated by Google Docs itself (exact pagination); otherwise the local
  // engine is used.
  const [google, setGoogle] = useState<GoogleStatus | null>(null)
  const refreshGoogle = useCallback(() => {
    googleStatusFn()
      .then((res) => {
        authGuard(res)
        setGoogle(res.ok ? res.data : null)
      })
      .catch(() => setGoogle(null))
  }, [])
  useEffect(refreshGoogle, [refreshGoogle])

  // The template is derived on demand from the document HTML — pure, and
  // cached across components so the document parses once per change.
  const template = useMemo(
    () =>
      editorHtml.trim()
        ? buildTemplateCached(editorHtml, editorCss, editorTitle, templateUrl || 'editor', editorBodyClass)
        : null,
    [editorHtml, editorCss, editorTitle, templateUrl, editorBodyClass],
  )

  const unbound = unmappedTags(template, data?.columns ?? [], mapping, ruleBindings)

  const plan: GenerationPlan | null = useMemo(() => {
    if (!template || !data) return null
    return {
      template,
      data,
      // Rule-text tags need column values too, so map the full tag set.
      mapping: effectiveMapping(allPlanTags(template, ruleBindings), data.columns, mapping),
      ruleBindings,
      tagFormats,
      group,
    }
  }, [template, data, mapping, ruleBindings, tagFormats, group])

  // Preview: the group LIST is cheap; only the visible document is resolved
  // (resolving all 500 groups of a big batch froze the tab on every switch).
  const previewGroups = useMemo(
    () => (view === 'preview' && plan ? planGroups(plan) : []),
    [view, plan],
  )
  const currentGroup =
    previewGroups[Math.min(previewIndex, Math.max(0, previewGroups.length - 1))] ?? null
  const currentPreviewHtml = useMemo(
    () => (plan && currentGroup ? resolveGroupDocument(plan, currentGroup, 'placeholder') : null),
    [plan, currentGroup],
  )

  const generateBlockedReason = !template
    ? 'Escribe o carga primero la plantilla'
    : !data
      ? 'Carga primero los datos'
      : template.tags.length === 0
        ? 'Inserta al menos un campo en el documento'
        : unbound.length > 0
          ? `Faltan datos por vincular: ${unbound.join(', ')}`
          : null

  // Used columns with empty cells: a blank in a legal document is silent and
  // dangerous, so GenerateDialog shows these as a non-blocking warning.
  const emptyCellWarnings = useMemo(() => {
    if (!plan) return []
    const used = [...new Set(Object.values(plan.mapping).filter((c): c is string => !!c))]
    const warnings: string[] = []
    for (const col of used) {
      const empty = plan.data.rows.filter((r) => !(r[col] ?? '').trim()).length
      if (empty > 0) warnings.push(`«${col}» no tiene valor en ${empty} de ${plan.data.rows.length} filas`)
    }
    return warnings
  }, [plan])

  const totalTags = template ? allPlanTags(template, ruleBindings).length : 0
  const boundCount = totalTags - unbound.length
  const hasWork = Boolean(editorHtml.trim() || data || templateUrl.trim())

  // Generation jobs resolve every group ONCE when the dialog opens (an inline
  // call would re-resolve the whole batch on every re-render while it's open).
  const generateJobs = useMemo(
    () =>
      generateOpen && plan
        ? renderDocuments(plan, 'empty').map((d) => ({ name: d.key, html: d.html }))
        : [],
    [generateOpen, plan],
  )

  // Native route (materialise the ORIGINAL Drive file) is decided only while
  // previewing or generating: the check normalises the whole document HTML,
  // too heavy to run on every keystroke in edit mode.
  const needsNativeDocument = generateOpen || view === 'preview'
  const nativeRoute = useMemo(
    () =>
      needsNativeDocument
        ? decideNativeRoute({ sourceFile, editorHtml, editorCss, ruleBindings })
        : null,
    [needsNativeDocument, sourceFile, editorHtml, editorCss, ruleBindings],
  )
  const native = useMemo(
    () =>
      generateOpen && plan && sourceFile && nativeRoute?.eligible
        ? {
            sourceFileId: sourceFile.id,
            jobs: buildNativeJobs(plan, sourceFile.tagLiterals, nativeRoute.edits, nativeRoute.styles ?? []),
          }
        : null,
    [generateOpen, plan, sourceFile, nativeRoute],
  )
  const nativePreviewJob = useMemo(() => {
    if (
      view !== 'preview' ||
      !plan ||
      !sourceFile ||
      !nativeRoute?.eligible ||
      !currentGroup
    )
      return null
    return buildNativeJobs(plan, sourceFile.tagLiterals, nativeRoute.edits, nativeRoute.styles ?? [])[
      Math.min(previewIndex, previewGroups.length - 1)
    ] ?? null
  }, [view, plan, sourceFile, nativeRoute, currentGroup, previewIndex, previewGroups.length])

  const fieldsState: StepState =
    !template || totalTags === 0 ? 'muted' : unbound.length > 0 ? 'warn' : 'ok'

  return (
    <div className="mx-auto flex h-screen max-w-[110rem] flex-col gap-3.5 px-5 py-4">
      <header className="flex items-center gap-3">
        <Link
          to="/"
          className="inline-flex items-center gap-1.5 rounded-lg border border-hairline bg-surface px-3 py-1.5 text-sm font-medium text-ink-secondary shadow-e1 outline-none hover:text-primary focus-visible:ring-2 focus-visible:ring-primary"
        >
          <Home className="h-3.5 w-3.5" /> Inicio
        </Link>
        <FileStack className="h-5 w-5 text-accent-sky" />
        <h1 className="text-lg font-bold tracking-tight text-ink">Generador de documentos</h1>
        <div className="ml-auto flex items-center gap-3">
          <button
            onClick={() => setSaveOpen(true)}
            disabled={!editorHtml.trim()}
            className="inline-flex items-center gap-1.5 rounded-lg border border-hairline bg-surface px-3.5 py-1.5 text-sm font-medium text-ink-secondary shadow-e1 outline-none hover:text-primary focus-visible:ring-2 focus-visible:ring-primary disabled:opacity-40"
            title="Guarda el documento con sus campos, el enlace de datos, los vínculos y la agrupación en la biblioteca"
          >
            <Save className="h-3.5 w-3.5" /> Guardar plantilla
          </button>
          <GoogleConnect status={google} onChanged={refreshGoogle} />
        </div>
      </header>

      <TopBar
        canGenerate={!generateBlockedReason}
        generateBlockedReason={generateBlockedReason}
        onGenerate={() => setGenerateOpen(true)}
        google={google}
      />

      {/* Flow status: what is done, what is missing, why Generate is blocked
          (the reason used to live only in a hover tooltip). */}
      <div className="flex flex-wrap items-center gap-2.5 px-0.5 text-xs">
        <StepPill n={1} state={template ? 'ok' : 'muted'}>
          Plantilla
        </StepPill>
        <StepJoint done={Boolean(template && data)} />
        <StepPill n={2} state={data ? 'ok' : 'muted'}>
          Datos{data ? ` · ${data.rows.length} ${data.rows.length === 1 ? 'fila' : 'filas'}` : ''}
        </StepPill>
        <StepJoint done={fieldsState === 'ok'} />
        <StepPill n={3} state={fieldsState}>
          Campos
          {template && totalTags > 0 ? ` · ${boundCount}/${totalTags} vinculados` : ''}
        </StepPill>
        <span
          role="status"
          className={`inline-flex items-center gap-1.5 font-semibold ${
            generateBlockedReason ? 'text-accent-orange' : 'text-accent-green'
          }`}
        >
          {generateBlockedReason ? null : <CircleCheck className="h-4 w-4" />}
          {generateBlockedReason ?? 'Listo para generar.'}
        </span>
        {group.mode === 'per_row' && editorHtml.includes('data-ttg-repeat') ? (
          <span className="text-accent-orange">
            Hay secciones repetibles, pero en «un documento por fila» no se repiten: cambia a «un
            documento por grupo».
          </span>
        ) : null}
        {hasWork ? (
          <button
            onClick={() => setConfirmReset(true)}
            className="ml-auto inline-flex items-center gap-1.5 rounded-md px-2 py-1 text-xs text-ink-faint outline-none hover:bg-black/5 hover:text-ink-secondary focus-visible:ring-2 focus-visible:ring-primary"
          >
            <RotateCcw className="h-3 w-3" /> Empezar de nuevo
          </button>
        ) : null}
      </div>

      <div className="flex min-h-0 flex-1 gap-3.5">
        <Palette canvas={canvasRef} />

        <main className="relative min-w-0 flex-1">
          {/* The canvas stays mounted (hidden) in preview mode so the iframe
              keeps its state; the preview renders on top. */}
          <DocCanvas ref={canvasRef} className={view === 'edit' ? 'h-full' : 'hidden'} />

          {view === 'preview' ? (
            <div className="flex h-full flex-col gap-2">
              {previewGroups.length > 1 ? (
                <label className="flex items-center gap-2 text-sm text-ink-secondary">
                  Ver documento
                  <select
                    value={previewIndex}
                    onChange={(e) => setPreviewIndex(Number(e.target.value))}
                    className="max-w-[18rem] rounded-lg border border-hairline bg-surface px-2 py-1.5 text-sm outline-none focus:border-primary"
                  >
                    {previewGroups.map((g, i) => (
                      <option key={i} value={i}>
                        {g.key} {g.rows.length > 1 ? `(${g.rows.length} filas)` : ''}
                      </option>
                    ))}
                  </select>
                </label>
              ) : null}
              {currentPreviewHtml ? (
                google?.connected && sourceFile && nativePreviewJob ? (
                  <NativePreviewFrame
                    sourceFileId={sourceFile.id}
                    job={nativePreviewJob}
                    fallbackHtml={currentPreviewHtml}
                    className="min-h-0 flex-1"
                  />
                ) : (
                  <PreviewFrame html={currentPreviewHtml} className="min-h-0 flex-1" />
                )
              ) : (
                <p className="text-sm text-ink-faint">Nada que previsualizar todavía.</p>
              )}
            </div>
          ) : null}
        </main>
      </div>

      {generateOpen && plan ? (
        <GenerateDialog
          jobs={generateJobs}
          native={native}
          nativeFallbackReason={nativeRoute && !nativeRoute.eligible ? nativeRoute.reason : null}
          google={google}
          warnings={emptyCellWarnings}
          batchLabel={editorTitle}
          onClose={() => setGenerateOpen(false)}
        />
      ) : null}

      {confirmReset ? (
        <ConfirmDialog
          title="¿Empezar de nuevo?"
          body="Se vaciará la plantilla, los datos y los vínculos actuales. Las plantillas guardadas en «Mis plantillas» no se tocan."
          confirmLabel="Vaciar todo"
          onConfirm={() => {
            reset()
            setConfirmReset(false)
            notify('Espacio de trabajo vaciado.')
          }}
          onCancel={() => setConfirmReset(false)}
        />
      ) : null}

      {saveOpen ? <SaveRecipeDialog onClose={() => setSaveOpen(false)} /> : null}

      <Toast text={notice} token={noticeToken} onDismiss={clearNotice} />
    </div>
  )
}

type StepState = 'ok' | 'warn' | 'muted'

/** One step of the flow stepper: a numbered circle (check when done) in a pill. */
function StepPill({ n, state, children }: { n: number; state: StepState; children: React.ReactNode }) {
  const wrap: Record<StepState, string> = {
    ok: 'bg-accent-green/10 text-accent-green',
    warn: 'bg-accent-orange/10 text-accent-orange',
    muted: 'border border-hairline bg-surface text-ink-muted',
  }
  const dot: Record<StepState, string> = {
    ok: 'bg-accent-green text-white',
    warn: 'bg-accent-orange text-white',
    muted: 'bg-hairline text-ink-muted',
  }
  return (
    <span
      className={`inline-flex h-[30px] items-center gap-1.5 rounded-full py-0 pl-1.5 pr-3 text-xs font-medium ${wrap[state]}`}
    >
      <span className={`flex h-[18px] w-[18px] items-center justify-center rounded-full text-[10px] font-semibold ${dot[state]}`}>
        {state === 'ok' ? <Check className="h-2.5 w-2.5" strokeWidth={3.5} /> : state === 'warn' ? '!' : ''}
      </span>
      {n} · {children}
    </span>
  )
}

/** Connector line between two steps; green when the left step is done. */
function StepJoint({ done }: { done: boolean }) {
  return <span aria-hidden className={`h-0.5 w-5 rounded-full ${done ? 'bg-accent-green/30' : 'bg-hairline'}`} />
}
